# Project config file
# Available .yaml or .json file
# (data_list file is only used .json file)

{   "project_id": 1,  # 現状未使用

    "features": {
      "rasterLayers": {
        "enabled": true,  # ラスターレイヤー描画機能
        "layerSelectionPanel": true,  # レイヤー選択機能
        "layerSettingsUI": false,  # レイヤーのカラーマップなど操作する機能. これがtrueの時はlayerSelectionPanelもtrueの必要がある。
        "initmap": true  # 初期表示するか否か。する場合、データ定義のjsonの最初のラスターデータを表示する。
      },
      "vectorLayers": {
        "enabled": true,  # ベクターレイヤー描画機能
        "layerPanel": true,  # 現状これは常にtrue. ベクターチェックボックス
        "propertySelection": false,  # ベクターレイヤー操作機能
        "loadGeojson": false  # Geojsonファイルload機能
      },
      "markers": {
        "csvImport": true  # csv load機能
      },
      "mapControls": {
        "homeButton": true  # homeButton機能. 常にtrue
      }
    }
}
  